{"trial_id": "01", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "dense_units", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_rate", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001, 1e-05], "ordered": true}}], "values": {"dense_units": 96, "dropout_rate": 0.5, "learning_rate": 0.001}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/os/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/os/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/os/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/home/os/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"/home/os/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"/home/os/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 155, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"/tmp/ipykernel_101439/1314711595.py\", line 19, in build\n    model = tf.keras.Model(inputs=self.base_model.input, outputs=output)\n  File \"/home/os/.local/lib/python3.10/site-packages/keras/src/utils/tracking.py\", line 26, in wrapper\n    return fn(*args, **kwargs)\n  File \"/home/os/.local/lib/python3.10/site-packages/keras/src/models/functional.py\", line 135, in __init__\n    Function.__init__(self, inputs, outputs, name=name, **kwargs)\n  File \"/home/os/.local/lib/python3.10/site-packages/keras/src/ops/function.py\", line 77, in __init__\n    (nodes, nodes_by_depth, operations, operations_by_depth) = map_graph(\n  File \"/home/os/.local/lib/python3.10/site-packages/keras/src/ops/function.py\", line 331, in map_graph\n    raise ValueError(\nValueError: The name \"dropout\" is used 2 times in the model. All operation names should be unique.\n"}